const products = [
  {
    id: 1,
    name: "Wireless Bluetooth Earbuds",
    brand: "SoundCore",
    price: 49.99,
    category: "Electronics",
    stock: 120,
    rating: 4.5,
    description: "High quality bass, noise reduction, 24hr battery backup.",
  },
  {
    id: 2,
    name: "Mechanical Keyboard",
    brand: "RedDragon",
    price: 79.99,
    category: "Computer Accessories",
    stock: 50,
    rating: 4.7,
    description: "RGB backlit mechanical keyboard with blue switches.",
  },
  {
    id: 3,
    name: "Gaming Mouse",
    brand: "Razer",
    price: 39.99,
    category: "Computer Accessories",
    stock: 200,
    rating: 4.4,
    description: "Ergonomic design, 6 programmable buttons.",
  },
  {
    id: 4,
    name: "4K Monitor 27 inch",
    brand: "LG",
    price: 299.99,
    category: "Electronics",
    stock: 35,
    rating: 4.8,
    description: "Ultra HD IPS display with HDR support.",
  },
  {
    id: 5,
    name: "USB-C Fast Charger",
    brand: "Anker",
    price: 19.99,
    category: "Accessories",
    stock: 300,
    rating: 4.6,
    description: "20W fast charging adapter for phones.",
  },
  {
    id: 6,
    name: "Smart Watch",
    brand: "Amazfit",
    price: 89.99,
    category: "Wearable",
    stock: 65,
    rating: 4.3,
    description:
      "Fitness tracking, heart rate monitoring, 10-day battery life.",
  },
  {
    id: 7,
    name: "Portable SSD 1TB",
    brand: "Samsung",
    price: 109.99,
    category: "Storage",
    stock: 80,
    rating: 4.9,
    description: "Super fast NVMe external SSD for data transfer.",
  },
  {
    id: 8,
    name: "Laptop Stand",
    brand: "MI",
    price: 14.99,
    category: "Accessories",
    stock: 150,
    rating: 4.2,
    description: "Aluminum adjustable laptop stand.",
  },
  {
    id: 9,
    name: "Wireless Router",
    brand: "TP-Link",
    price: 59.99,
    category: "Networking",
    stock: 90,
    rating: 4.1,
    description: "Dual band WiFi router with long range coverage.",
  },
  {
    id: 10,
    name: "Power Bank 20000mAh",
    brand: "Realme",
    price: 24.99,
    category: "Electronics",
    stock: 100,
    rating: 4.5,
    description: "Fast charging power bank for on-the-go usage.",
  },
  {
    id: 11,
    name: "Smart LED Bulb",
    brand: "Philips",
    price: 12.99,
    category: "Home",
    stock: 400,
    rating: 4.3,
    description: "Color changing smart bulb with mobile control.",
  },
  {
    id: 12,
    name: "Bluetooth Speaker",
    brand: "JBL",
    price: 59.99,
    category: "Audio",
    stock: 70,
    rating: 4.6,
    description: "Portable speaker with deep bass and waterproof build.",
  },
  {
    id: 13,
    name: "Graphics Tablet",
    brand: "Wacom",
    price: 89.99,
    category: "Professional",
    stock: 45,
    rating: 4.7,
    description: "Drawing tablet for digital art and illustration.",
  },
  {
    id: 14,
    name: "Webcam 1080p",
    brand: "Logitech",
    price: 39.99,
    category: "Computer Accessories",
    stock: 140,
    rating: 4.4,
    description: "HD webcam with auto focus and clear microphone.",
  },
  {
    id: 15,
    name: "Noise Cancelling Headphones",
    brand: "Sony",
    price: 149.99,
    category: "Audio",
    stock: 30,
    rating: 4.9,
    description: "Premium ANC headphones for immersive sound.",
  },
  {
    id: 16,
    name: "Smartphone Tripod",
    brand: "Ulanzi",
    price: 29.99,
    category: "Accessories",
    stock: 250,
    rating: 4.2,
    description: "Mobile tripod with adjustable height and grip.",
  },
  {
    id: 17,
    name: "Laptop 15.6 inch",
    brand: "Acer",
    price: 499.99,
    category: "Computers",
    stock: 20,
    rating: 4.3,
    description: "Core i5 12th gen with 8GB RAM and 512GB SSD.",
  },
  {
    id: 18,
    name: "Gaming Chair",
    brand: "Cougar",
    price: 199.99,
    category: "Furniture",
    stock: 15,
    rating: 4.6,
    description: "Ergonomic gaming chair with lumbar support.",
  },
  {
    id: 19,
    name: "Portable Projector",
    brand: "Xiaomi",
    price: 159.99,
    category: "Home Entertainment",
    stock: 25,
    rating: 4.4,
    description: "Mini projector suitable for movies and presentations.",
  },
  {
    id: 20,
    name: "Air Purifier",
    brand: "Dyson",
    price: 249.99,
    category: "Home",
    stock: 12,
    rating: 4.8,
    description: "Removes dust, pollen, and allergens from air.",
  },
  {
    id: 21,
    name: "External Hard Drive 2TB",
    brand: "Western Digital",
    price: 69.99,
    category: "Storage",
    stock: 85,
    rating: 4.5,
    description: "Reliable portable hard disk for files and backup.",
  },
];

/***
 *ToDo  process-->
 *ToDo  Filter ==> Electronics
 *ToDo  sort by ==>rating
 *ToDo  slice==>first 3 (top 3)
 *ToDo  map ==> transform in the object shape to {productName:"name"}
 * */

const topElectronicsProducts = products
  .filter((product) => product.category === "Electronics")
  .sort((a, b) => b.rating - a.rating)
  .slice(0, 3)
  .map((item) => {
    return { productName: item.name, brand: item.brand };
  });

console.log(topElectronicsProducts);
